### PR TITLE
Draft Content: Code of Conduct

### PR DESCRIPTION
**Pull request by yacmov**
This pull request adds draft content for the Code of Conduct file, building upon the outline already established by Isaac-Saleh. The draft focuses on the following sections:

- Scope: This section clarifies where the code of conduct applies (e.g., online platform, in-person events).
- Enforcement: This section outlines the process for reporting violations and potential consequences.
- Enforcement Guidelines: This section details factors considered when determining appropriate consequences for violations.

**Please note**: This content is a draft and open for discussion.

### CODE REVIEW

**Review by Isaac-Saleh — CHANGES_REQUESTED** [review]
Hey Sukhwan, 
The scope looks really good. 

I think the Enforcement and Enforcement Guidelines could be a little more. 

Here is a recommended section from GitHubs Template. Maybe just list the stages of enforcement similar to what they have with the:

Correction/Warning/Temporary Ban/ Permanent Ban??

Thanks Zac

[Enforcement Example.txt](https://github.com/Isaac-Saleh/shared_documents_for_IPOS-final_proj/files/15301883/Enforcement.Example.txt)

**Comment by yacmov** [comment]
I will update tonight😊

**Comment by yacmov** [comment]
I've just modified as templet.

**Review by Isaac-Saleh — APPROVED** [review]
Thanks Sukhwan, 

I'll merge those changes in. 

Ta

**Pull request merged**
